spring:
  application:
    name: likelion-spring

  datasource:
    url: jdbc:mysql://likelion-database.cnu062wqeaz4.ap-northeast-2.rds.amazonaws.com/likelion
    username: likelion
    password: likelion